- .github/workflows/hourly.yml
- scripts/triage
This workflow searches for all issues which are not in the `Planning`
project and adds them to the project in the `Triage` column. We do this
at the bottom of the hour so that the `Triage` column is fresh for any
meetings we might have to do triage.
> Implement an hourly triage workflow

- scripts/triage
We now use two queries to separate the types of items we want to triage.
Also, we ignore conference issues.
> Simplify triage

- .github/workflows/hourly.yml
- scripts/auto-merge
This code implements auto-merge for the Enarx organization bot.
While functionally complete, I'm submitting in draft form until I know the name of the encrypted secret to use (currently `secrets.BOT_TOKEN`).
The code is intended to run every 15 minutes (with `cron` syntax). For faster testing, it's currently set to run every 5 minutes. When run, it will leave logs about which PRs were and were not auto-merged.
It currently runs on the [enarxbot-test-org](https://github.com/enarxbot-test-org) organization for testing.
> Implement auto-merge bot functionality

- scripts/prstate
After thinking on this a bit, I want to move to a simpler responsibility
model. While there are any outstanding `CHANGES_REQUESTED`, the PR is
the responsiblity of the author. Otherwise, the PR is the responsibility
of the people who have been requested for review and the previous
reviewers who have had their reviews `DISMISSED`. The latter condition
captures reviewers who have accepted a PR, but then the author pushed
additional changes. In this case, the reviewer must re-review.
This responsibility model also has the nice property that reviewers
aren't responsible to re-review a PR until the author addresses all
outstanding reviews. Without this, reviews might become interleaved
which could result in conflicting requirements and a general increase of
disruption of engineer thought …
> Rewrite prstate action

- .github/workflows/hourly.yml
- scripts/assigned
- scripts/common.py
- scripts/merge
- scripts/prstate
- scripts/triage
We use the bot container which has pygithub and nginx set up for us.
Then we proxy all requests through the nginx proxy. Repeated requests
will be cached. This increases performance and reduces the number of API
calls we make all the way to GitHub's servers.
> Enable a local caching proxy for all bot requests

- Dockerfile
- enarx-assigned
- enarx-triage
- enarxbot.py
Github seems to sometimes return stale results when looking for issues that are not in a project. This was causing bot failures when we attempted to add such issues to a project they were already in.
This commit adds error handling around those calls, allowing them to fail gracefully.
> Make project card additions fail gracefully

- Dockerfile
Container uses Python 3.9 instead of 3.8.
> Fix Python import path

- enarx-assigned
- enarx-merge
- enarx-prstate
- enarx-triage
- enarxbot.py
This is only available in GitHub's graphql queries. So we create an object that bridges the gap between the v3 and v4 APIs.
> Provide a way to query for suggested reviwers

- enarx-pr-merge
This PR rewrites the `merge` action to merge PRs in ascending order of the time of last approval.
It's a little messy, I haven't tested it yet, and it may need changes, so I'm submitting in draft form.
Resolves #30.
> Ensure merge order

- enarx-pr-assign
Currently, a single CHANGES_REQUESTED review causes the ticket to be assigned
to the PR author and any additional requested reviewers who have not replied.
This has two negative consequences. First, there is no way to clearly place a
PR in the author's responsibility. For example: "Should we close this PR?"
Second, this encourages reviewers to submit reviews on top of ongoing changes
the author might make. This can only create frustration.
Therefore, this patch makes it ONLY the PR author's responsibility whenever a
CHANGES_REQUESTED review is submitted. No further reviews are needed until the
author addresses the current review.
> Assign PRs to their authors on any CHANGES_REQUESTED reviews

- .github/workflows/hourly.yml
- enarx-pr-request
We might want to move this logic wherever we decide to implement PR auto-assignments, but I've put it in a standalone file for now.
Resolves #26.
> Auto-request reviewers on PRs that have fewer than three requests

- enarx-pr-request
This proposes two new strategies for the script:
1. Use login strings rather than User objects in the sets.
2. Make sets mutually exclusive early on.
Based on this, calculating the set of users to request becomes straightforward.
Also, add support for user status. We will not assign busy users.
> Simplify enarx-pr-request and handle busy

- enarx-pr-request
The bot was re-requesting those already requested on the PR. This makes it such that the bot only requests those that are newly requested.
> Fix the bot re-requesting everyone already requested on the PR

- enarx-assigned
This is so issues may be assigned elsewhere on the board, but not automatically added to the Sprint board unless explicitly in the "Assigned" column of the Planning board.
Resolves #18.
> Limit `assigned` action to issues from "Assigned" column in Planning

- .github/workflows/manual.yml
- enarx-post-sprint-cleanup
This action is triggered manually, under the "Actions" tab of the `enarx/bot` repo. It moves all issues in the "Assigned" tab of the sprint board to the "Nominated" tab; intended to be used at end-of-sprint retrospectives.
This needs #20 in order to work correctly; otherwise, issues will be automatically moved back to the Sprint board if they're still assigned.
Resolves #17.
> Implement an action for manual end-of-sprint board cleanup

- enarx-post-sprint-cleanup
1) If a card already existed on the Planning board, the corresponding card on the Sprint board would not get deleted.
2) If a card did exist on the Planning board, the loop would not break out correctly, and the bot would attempt to add the same card again.
Given the bot fails project card additions gracefully now, this might actually not change functionality. But it should save some API calls.
> Fix some logic errors in sprint board cleanup

- enarx-assigned
Attempting to fetch card content of a specific type (ex: `Issue` ) would result in a 404 if the card didn't have that content (ex. if the card was a `PullRequest`). This patch fetches the content without specifying type and then checks its type directly in code.
> Fix 404 error when attempting to fetch assigned issues/PRs

- enarx-assigned
A while back, we made a change to the `enarx-assigned` action to prevent assigned issues from moving to the Sprint board unless they were in the Assigned column (see [here](https://github.com/enarx/bot/pull/20)). At the time, I also made the same change for PRs. However, given our end-of-sprint board cleanup only touches issues and not PRs, this was ultimately redundant. Additionally, it may have inadvertently prevented some PRs from being moved to the "Reviewing" column, which is not ideal.
This fixes that bug by reverting the changes made in the mentioned patch just for pull requests, and thus making it such that all assigned PRs on the Planning board also get added to the Sprint board's "Reviewing" column. This shouldn't impact sprint or board functionality; in fact, it's probably …
> Fix a bug preventing PRs from appearing on the Sprint board

- action.yml
- enarxbot-triage
The `enarxbot-pr-triage` action currently in the repo only worked on pull requests. This should make it work on issues as well.
The GraphQL data returned is structured the same regardless of the event that triggered it, so there's not much change to the logic at all -- just some generalization renames, as well as making it run and accept issue events.
> Make enarxbot-pr-triage run and work on issues

- bot.py
- enarxbot-triage
This should allow us to specify as many GraphQL depagination fields as we want in a single request, including nested depagination.
> Support arbitrary amounts of GraphQL depagination in a single request

- action.yml
- bot.py
- enarxbot-pr-merge
Converts the auto-merge bot action to use pure GraphQL, and to run as a scheduled action on implementing repos.
This is purely additive; the existing bot functionality should continue to work. If used, this action would simply run all the PR-related scripts when a pull request target event happens.
> Convert `enarx-pr-merge` to GraphQL, and make it consumable by other repos

- enarxbot-pr-merge
`enarxbot-pr-merge` is breaking because a cursor was not updated to the new format that supported multiple cursors.
> Fix an incorrectly formatted cursor

- enarx-pr-assign
> Prevent the bot from attempting to assign dependabot to PRs

- enarx-pr-assign
- enarx-pr-request
- enarxbot.py
This should be a quick band-aid for the current bot failures.
> Make insufficient repo permissions a soft failure

- action.yml
- enarxbot-copy-labels-linked
This action is the last that needs to be re-implemented using the new bot strategy. Once #55, #66, and this are merged, I can start on #74.
> Re-implement copy-labels-linked in GraphQL and events

- action.yml
- enarxbot-pr-assign
Rewrites the event-parsing logic in the `pr-assign` action to use Github's GraphQL API.
> Rewrite `enarx-pr-assign` as consumable with GraphQL

- action.yml
- enarxbot-pr-request
This is a pretty significant rewrite. Though the logic for selecting reviewers is much the same as in the original, the API interaction has changed significantly.
Thanks to the information available to us from the `pull_request_target` event this action runs on, I was able to pull down _everything_ needed for this action in a single GraphQL call. This includes things like availability information and user IDs (necessary for the final GraphQL mutation). Some pre-processing indexes this info by username so it can be looked up when needed; all the selection logic uses login strings only, just like before.
All told, this should only make two calls to Github per invocation.
> Rewrite `enarx-pr-request` as consumable with GraphQL

- .github/workflows/sprint-board-cleanup.yml
- enarxbot-post-sprint-cleanup
This will allow us to remove all traces of PyGithub and API v3 from the Enarxbot.
> Rewrite sprint board cleanup in GraphQL

- .github/workflows/sprint-board-cleanup.yml
This was causing `enarxbot-post-sprint-cleanup` to fail.
> Fix post-sprint-cleanup not checking out the repo properly

- enarxbot-pr-assign
This should also prevent attempting to assign non-valid users (like bots) to PRs.
> Fix a key error in enarxbot-pr-assign

- enarxbot-pr-assign
> Deeper fix for enarxbot-pr-assign failing when encountering a bot

- bot.py
- enarxbot-assigned
- enarxbot-copy-labels-linked
- enarxbot-post-sprint-cleanup
- enarxbot-pr-assign
- enarxbot-pr-merge
- enarxbot-pr-request
- enarxbot-triage
This should make the bot explicitly opt-in for things like forks. If `BOT_TOKEN` is not set, all running scripts will fail gracefully, with a message explaining how to opt in using a properly-provisioned token.
Note this is a breaking change, and will require workflows using the Enarxbot to be updated to not overwrite `GITHUB_TOKEN`.
> Require a properly-set BOT_TOKEN environment variable to run automation

- bot.py
Even if the `BOT_TOKEN` secret itself is unset, the environment variable would be set, but empty. This updates the token validity check to account for that: the token must also be longer than 0 in length in order to proceed.
> Fix a bug with BOT_TOKEN requirement

- enarxbot-assigned
When `enarx-pr-assign` runs, it often assigns three people at once when a PR is first opened. This fires three separate `pull_request_target` `assigned` events. If that PR is not on the sprint board, this scenario causes a race condition between all three events, which causes a failure when one of the events attempts to add a card that's already present.
This just makes project addition errors a soft failure. Short of a mutex across different Actions, this is the best solution.
See [here](https://github.com/enarx/bot/runs/1344462942?check_suite_focus=true) for an example failure this would fix.
> Fix race condition when moving PRs to sprint board

- .github/workflows/sprint-board-cleanup.yml
> Fix unset BOT_TOKEN for sprint board cleanup

- enarxbot-assigned
- enarxbot-triage
`GraphQLError` was not being handled correctly when thrown in `enarxbot-assigned`. That has been fixed, and the error handling has also been extended to `enarxbot-triage`, which may perform the same API call but didn't have error handling on it.
> Fix bug w/ project card error handling and apply to both actions
